### PR TITLE
Add error messages in require() in TokenNetwork

### PR DESCRIPTION
**Pull request by pirapira**
And turn on the optimizer of the Solidity compiler.  Otherwise, the runtime bytecode becomes too big for deployment.

This is a part of https://github.com/raiden-network/raiden-contracts/issues/81

### CODE REVIEW

**Comment by hackaugusto** [comment]
What about the other solidity files?

**Comment by pirapira** [comment]
> There are places missing messages, checked with

I'll see.  By the way `assert()`s don't fail.

> What about the other solidity files?

Will be kept track in #81.

**Comment by pirapira** [comment]
I'll try to keep the optimizer off, by splitting away the messages into a different contract and saving the codesize.

**Comment by pirapira** [comment]
@hackaugusto `assert()` is implemented using `INVALID` opcode, which cannot return a message anyway.

**Comment by pirapira** [comment]
When I move the strings to a library, the runtime code becomes bigger.  So a serious split up is necessary https://github.com/raiden-network/raiden-contracts/issues/401 .

**Pull request closed without merging**
