### PR TITLE
add coincurve to requirements

### PR DESCRIPTION
**Pull request by czepluch**
Discovered that `coincurve` was missing when I tried to run the tests.

### CODE REVIEW

**Comment by hackaugusto** [comment]
@loredanacirstea , this repo will also include the python utilities? I thought the goal of this repo was to be a language agnostic way to distribute the smart contracts

**Comment by loredanacirstea** [comment]
@hackaugusto 
You are right, so we should have a `requirements-dev.txt` for testing & building. Otherwise, just provide the contracts source code + a variable that exports the contracts.json compiled data. Right?

**Comment by pcppcp** [comment]
From what I understand this repo is intended to be used for development of the smart contracts. This obviously requires a set of tools & testsuite and Python is a obvious choice here. I don't see any point in having a separate repository just for solidity files.

Since several projects need to use smart contracts ABI without duplicating the code, the repository should also provide a simple python library that'll provide an easy way of getting data required to instantiate `Contract` classes from python web3/ethereum libs.
The library must provide
1) a dumb interface for getting ABI/event ABI (it'll just read the compiled `contracts.json` and return whatever it finds there)
2) an optional contract manager capable of using `solc` to compile bytecode, with possibility to use contract libraries. This is required for deploying contracts on tester chains in individual projects (See Paul's comment at #11 ). If `solc` is missing, this functionality won't be available.

**Comment by loredanacirstea** [comment]
This discussion is off-topic here. It should be continued in https://github.com/raiden-network/raiden-contracts/issues/10 and the issue should be close after we settle on what the package should export.

**Pull request merged**
