### PR TITLE
Revert data to data_0.25.2

### LINKED ISSUE #1300: revert `data` to where `data_0.25.2`
because we will be working on `data_0.25.2` for a while.

### PR DESCRIPTION
**Pull request by pirapira**
We have deployed our contracts to the mainnet and we are no longer
making frequent deployments.  But we have to be ready to
patch the Solidity contracts.  So our current Solidity sources
must be what have been deployed.

data_0.25.2 was once inconsistent #1298 partially because
we had edited the Solidity files in `data` directory.

This closes #1300.

### What this PR does

Reverts the contents of `data` to those of `data_0.25.2`.

### Why I'm making this PR

To prevent https://github.com/raiden-network/raiden/issues/5122 in the future.

### What's tricky about this PR (if any)

The PR was made very manually, so things might break.

----

Any reviewer can check these:

* [ ] Squash unnecessary commits
* [ ] Comment commits

And before "merge" all checkboxes have to be checked.  If you find redundant points, remove them.

### CODE REVIEW

**Comment by palango** [comment]
Is there any tool that I can use to verify that the contracts now match the deployed contracts?

**Comment by pirapira** [comment]
I connected to our node and did
```
eth.getCode(address)
```

copied and pasted the result to a file.  And eventually ran `diff`.

**Comment by palango** [comment]
So, that would mean for me:
- install `solc` 0.5.4
- run `make compile_contracts` on this PR
- `getCode` for the deployments
- compare the two

**Comment by karlb** [comment]
Do we really need to care about this in `raiden_contracts/data`? Don't we have `raiden_contracts/data_0.XX.0` for all cases where we need exactly the contracts as they were deployed? If we want to minimally patch a contract, we should branch off the respective release tag instead of keeping the current master branch is a specific state, shouldn't we?

**Comment by pirapira** [comment]
@karlb In this PR I am trying to prepare for minimally patched contracts. I think it's a good idea to have an `alderaan` branch. So I'll write down how to use the release branches https://github.com/raiden-network/raiden-contracts/issues/1327

**Pull request closed without merging**
