### PR TITLE
v0.13.0 release

### PR DESCRIPTION
**Pull request by pirapira**
Followed the release process for v0.13.0.  The main reason for making a release now is to make sure that the current contract interfaces work with other components of raiden.

### CODE REVIEW

**Comment by pirapira** [comment]
I'm breaking rules because this portion is the bottleneck now.

**Comment by BOR4** [comment]
paths like "raiden_contracts/data_0.9.0/data_0.8.0/source/raiden/TokenNetworkRegistry.sol" are intentional?

**Comment by pirapira** [comment]
No.  Sorry.

**Comment by BOR4** [comment]
yes. Looked strange :)

**Pull request merged**
