### PR TITLE
Move CHANGELOG.md into raiden_contracts

### PR DESCRIPTION
**Pull request by pirapira**
so that it's included in the package.

This is a part of #470.

### CODE REVIEW

**Comment by ulope** [comment]
The change does what it's supposed to but my question would by why you would want to include the changelog in the distribution package? I'd guess the likelihood of anyone ever seeing it in there is probably close to zero.

**Comment by pirapira** [comment]
Now I don't remember who asked me to do this.  So I can close this as well.

**Comment by pirapira** [comment]
At least @LefterisJP wants to see CHANGELOG.md in the package.

**Comment by pirapira** [comment]
> At least @LefterisJP wants to see CHANGELOG.md in the package.

That was not quite right.  He just wants CHANGELOG somewhere.

**Comment by pirapira** [comment]
GitHub does not follow symlinks automatically.  Maybe `distutils` does.  So the symlink should be placed in `raiden_contracts` package and point outwards.

**Comment by pirapira** [comment]
I close this and follow up in #470.

**Pull request closed without merging**
