### PR TITLE
Skip gas estimation to speed up tests

### PR DESCRIPTION
**Pull request by karlb**
This currently causes weird side-effects like transactions that used to
fail with gas cost estimation suddenly succeeding (or at least not
throwing `TransactionFailed`).

@pirapira This a the problem I talked to you about. I have no idea why this happens. Maybe you can give this PR a try.

### CODE REVIEW

**Comment by pirapira** [comment]
@karlb OK.  Took it.

**Comment by pirapira** [comment]
Yes, I see the problem.

```
====================================================== FAILURES =======================================================
___________________________________________ test_close_nonexistent_channel ____________________________________________
[gw1] linux -- Python 3.6.7 /home/yoichi/src/raiden-contracts/venv/bin/python3.6
                                                                                
token_network = <web3.utils.datatypes.Contract object at 0x7efdb0e4cb70>        
get_accounts = <function get_accounts.<locals>.get at 0x7efdb6946598>           
                                                                                
    def test_close_nonexistent_channel(                                         
            token_network,                                                      
            get_accounts,                                                       
    ):                                                                          
        """ Test getChannelInfo and closeChannel on a not-yet opened channel """
        (A, B) = get_accounts(2)                                                
        non_existent_channel_identifier = 1                                     
                                                                                
        (settle_block_number, state) = token_network.functions.getChannelInfo(
            channel_identifier=non_existent_channel_identifier,
            participant1=A,
            participant2=B,                                                                                            
        ).call()                                                                                                       
        assert state == ChannelState.NONEXISTENT                                                                                                                                               
        assert settle_block_number == 0
    
        with pytest.raises(TransactionFailed):
            token_network.functions.closeChannel(
                channel_identifier=non_existent_channel_identifier,
                partner=B,
                balance_hash=EMPTY_BALANCE_HASH,
                nonce=0,
                additional_hash=EMPTY_ADDITIONAL_HASH,
                signature=EMPTY_SIGNATURE,
>           ).transact({'from': A, 'gas': 81000})
E           Failed: DID NOT RAISE <class 'eth_tester.exceptions.TransactionFailed'>

raiden_contracts/tests/test_channel_close.py:40: Failed
```

**Comment by pirapira** [comment]
eth_tester has some [special code](https://github.com/ethereum/eth-tester/blob/1210ed1fea7864f7c6637c673339731e588f74f2/eth_tester/backends/pyevm/main.py#L510) to throw `TransactionFailed` during `estimate_gas`.

Now the question is how to test for a transaction's failure.

**Comment by pirapira** [comment]
If I say `call` instead of `transact`, again I see `TransactionFailed`.

**Comment by pirapira** [comment]
But when we use `transact()` with gas, we cannot rely on its success. Perhaps we have to use `check_successful_tx()` in `raiden_contracts.utils.transaction`.

**Comment by pirapira** [comment]
* When we expect failures, anyway, the gas estimation runs the transaction only once.  So there won't be any speedup from the current status.
* When we expect success,

**Comment by pirapira** [comment]
I guess `call_and_transact()` would work both for the success cases and the failure cases.

**Comment by karlb** [comment]
Can't we have a `transact_and_check_for_success`? I thought we were mining one block per transaction anyway and should be able to see the transaction status from the receipt.

**Comment by pirapira** [comment]
@karlb I tried that and the run took 48 minutes.  https://github.com/raiden-network/raiden-contracts/pull/802

**Comment by pirapira** [comment]
I found another interesting error.  For some reasons, the block gas limit is sometimes lower.  Maybe I can get away with lowering the always-used gas limit.

```
        close_and_update_channel(
            channel_identifier,
            A,
            values_A,
            B,
            values_B,
        )
    
        # Settle channel after a "long" time
        web3.testing.mine(settle_timeout + 50)
    
>       call_settle(token_network, channel_identifier, A, values_A, B, values_B)

raiden_contracts/tests/test_channel_unlock.py:1378: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
raiden_contracts/tests/fixtures/channel.py:759: in call_settle
    ).transact({'from': A})
venv/lib/python3.6/site-packages/web3/contract.py:1151: in transact
    **self.kwargs
venv/lib/python3.6/site-packages/web3/contract.py:1454: in transact_with_contract_function
    txn_hash = web3.eth.sendTransaction(transact_transaction)
venv/lib/python3.6/site-packages/web3/eth.py:263: in sendTransaction
    get_buffered_gas_estimate(self.web3, transaction),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

web3 = <web3.main.Web3 object at 0x7fa500d6e908>, transaction = {'data': '0x9cadb1590000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f41e03a869...34184bb7352', 'from': '0xF41e03a8693052a7084e206635558354C2140ea6', 'to': '0x82dd0e0eA3E84D00Cc119c46Ee22060939E5D1FC'}, gas_buffer = 100000

    def get_buffered_gas_estimate(web3, transaction, gas_buffer=100000):
        gas_estimate_transaction = dict(**transaction)
    
        gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
    
        gas_limit = get_block_gas_limit(web3)
    
        if gas_estimate > gas_limit:
            raise ValueError(
                "Contract does not appear to be deployable within the "
                "current network gas limits.  Estimated: {0}. Current gas "
>               "limit: {1}".format(gas_estimate, gas_limit)
            )
E           ValueError: Contract does not appear to be deployable within the current network gas limits.  Estimated: 5700000. Current gas limit: 5564350

venv/lib/python3.6/site-packages/web3/utils/transactions.py:92: ValueError
```

**Comment by pirapira** [comment]
Another PR based on this one, #805 was merged.

**Pull request closed without merging**
