### PR TITLE
Add SC Tests/Fixtures and some SC changes

### PR DESCRIPTION
**Pull request by pcppcp**
fixes https://github.com/raiden-network/raiden-contracts/issues/2
fixes https://github.com/raiden-network/raiden-contracts/issues/4

(LC:)
- add more tests and fixtures
- deploy script uses web3 directly; compiled contracts data must be provided (done with `populus compile`

Smart contract changes:
- `TokenNetworkRegistry` -> `TokenNetworksRegistry`
- block numbers are `uint256` instead of `uint64`
- add `chain_id` to `TokenNetwork`, `TokenNetworksRegistry` constructors 
- `event ChannelClosed(uint256 channel_identifier, address closing_address);` (replaced old argument `closing_participant`, because we provide the address of the caller - can be a 3rd party)
- support for closing & updating the channel without any existent off-chain transfers ('nonce' issue: https://github.com/raiden-network/raiden-contracts/pull/15/files#diff-1bdf2ff343918b98864fc26df16cc1ebR276)
- add channel data getters until we are able to return structs in Solidity: 
```
function getChannelInfo(
        uint256 channel_identifier)
        view
        external
        returns (uint256, address, uint256)
    {
        ....
        return (
            channel.settle_timeout,
            closing_request.closing_participant,
            closing_request.settle_block_number
        );
    }

function getChannelParticipantInfo(
        uint256 channel_identifier,
        address participant)
        view
        external
        returns (bool, uint256, uint256, uint64, bytes32)
    {
       ....
        return (
            participant_state.initialized,
            participant_state.deposit,
            participant_state.transferred_amount,
            participant_state.nonce,
            participant_state.locksroot
        );
    }

```

### CODE REVIEW

**Comment by hackaugusto** [comment]
> event ChannelClosed(uint256 channel_identifier, address closing_address); (replaced old argument closing_participant, because we provide the address of the caller - can be a 3rd party)

Why was this changed? Why is a third party allowed to call close? This should not be the case. Additionally, how can a node tell which direction of the channel was updated first without the closing_participant?

> support for closing & updating the channel without any existent off-chain transfers ('nonce' issue: https://github.com/raiden-network/raiden-contracts/pull/15/files#diff-1bdf2ff343918b98864fc26df16cc1ebR276)

why should **update** allow for a call if there is no data to be provided? what is the end result of this? (close must allow it)

**Comment by LefterisJP** [comment]
I understood it as delegate closing but let's see what @loredanacirstea says.

But if it's 3rd party (i.e. a monitor) closing then that's definitely not something to be allowed.

**Comment by loredanacirstea** [comment]
Naming for event argument reverted https://github.com/raiden-network/raiden-contracts/pull/19. There was no good reason to change this. Logic stayed the same. There is no 3rd party close.

**Comment by loredanacirstea** [comment]
> why should update allow for a call if there is no data to be provided? what is the end result of this? 
fixed: https://github.com/raiden-network/raiden-contracts/pull/20

**Pull request merged**
