### PR TITLE
Move Red Eyes 0.4.0 precompiled + deployment to a separate data folder

### PR DESCRIPTION
**Pull request by loredanacirstea**
fixes https://github.com/raiden-network/raiden-contracts/issues/437

**Breaking change for Raiden client**: 
- for using the Red Eyes version, you must use `ContractManager(contracts_precompiled_path('0.4.0'))`!
- for using the pre-Red Eyes, formerly known as `pre-limits` version, you must use `ContractManager(contracts_precompiled_path('0.3._'))`!

Now there are three versions supported in this package:

- Development `0.3._` contracts version (from `0.3.0` package release: https://github.com/raiden-network/raiden-contracts/releases/tag/v0.3.0). No limits on the number of tokens registered; has a limit of 100 tokens per channel). Source code: https://github.com/raiden-network/raiden-contracts/tree/fc1c79329a165c738fc55c3505cf801cc79872e4/raiden_contracts/contracts
- Red Eyes Mainnet `0.4.0` contracts version (from `0.7.0` package release: https://github.com/raiden-network/raiden-contracts/releases/tag/v0.7.0). Source code: https://github.com/raiden-network/raiden-contracts/tree/fac73623d5b92b7c070fdde2b446648ec9117474/raiden_contracts/contracts
- current !development version `0.5.x` corresponding with the `master` branch (might not be stable).

These are temporary and will be removed in favor of only one contracts version in the Ithaca Milestone.

Also added appropriate tests for file existence.

### CODE REVIEW

**Comment by loredanacirstea** [comment]
Needs contracts version bump to be done, to have a different version than the `0.4.0` Red Eyes contracts.

**Comment by LefterisJP** [comment]
> for using the pre-Red Eyes, formerly known as pre-limits version, you must use ContractManager(contracts_precompiled_path('0.3._'))!

Will this be supported only until your next release is ready or should we keep supporting this in the future? As far as the client is concerned it would now be:

- production -> `ContractManager(contracts_precompiled_path('0.4.0'))`
- development -> for now `ContractManager(contracts_precompiled_path('0.3._'))` and with each one of your releases follow latest release? Or just stick to that one?

From my comment [here](https://github.com/raiden-network/raiden-contracts/issues/437#issuecomment-453530836) I understood you meant that development version will always be the latest contract package release which has a deployment.

**Comment by loredanacirstea** [comment]
@LefterisJP 

> Will this be supported only until your next release is ready or should we keep supporting this in the future?

Only until https://github.com/raiden-network/raiden-contracts/issues/391 is done. Then the `0.3._` will be replaced by the development version - probably `0.5.x`

> production -> ContractManager(contracts_precompiled_path('0.4.0'))
development -> for now ContractManager(contracts_precompiled_path('0.3._'))

You can stick with these two for now. No need to support the current development version until `0.5.x` is out.

> From my comment here I understood you meant that development version will always be the latest contract package release which has a deployment.

Development version will be whatever version is in the `/data` folder.

**Comment by loredanacirstea** [comment]
Todo:
- add `bin-runtime` to the `0.4.0` precompiled data.
- test to check if the precompiled data for each version contains the expected data, for each contract. This currently is:
  - abi
  - bin
  - bin-runtime
  - metadata

**Pull request merged**
