### PR TITLE
Bump solc version

### PR DESCRIPTION
**Pull request by pcppcp**

### CODE REVIEW

**Comment by czepluch** [comment]
@pcppcp can you either close this or update to newer version?

**Comment by loredanacirstea** [comment]
Just be aware that we are not upgrading yet anyway. Version 0.4.22 is not stable.

**Comment by czepluch** [comment]
0.4.23 isn't stable either?

**Comment by LefterisJP** [comment]
We can get rid of a lot of warning by upgrading but 0.4.22 had a lot of problems so perhaps let's wait a few days before going to 0.4.23

**Comment by palango** [comment]
This was fixed by #57 as well.

**Pull request closed without merging**
